### ISSUE TITLE
Still active ?

### ISSUE THREAD

**Issue by hcarsten** [elkuku/EasyCreator#30]
just wondering if the components is still under active development ?
I just tried to run under Joomla 3.3 and did not got any success. just creating a "plain component" will fail with an "Error - An error happened while creating your project" !

so just wondering if there is any chance to get a skeleton for 3.3 been created with the tool ?

best

**Comment by elkuku** [comment]
Well, let's say "yes" :wink: 

I've just commited some latest changes, created a tag and updated the [entry in the JED](http://extensions.joomla.org/extensions/extension/miscellaneous/development/easycreator)...

So please check out the latest version here: https://github.com/elkuku/EasyCreator/releases

and report any strange things that might happen...

THANKS for reminding me of this project :wink:

**Comment by Bodge-IT** [comment]
Love this app, looking to use it in anger soon!
Thanks for the update.

**Comment by elkuku** [comment]
still active :wink:
