### ISSUE TITLE
Joomla 3.3.x EcrProjectTypePlugin::getCoreProjects - Unknown J! version

### ISSUE THREAD

**Issue by stefano-buscaglia** [elkuku/EasyCreator#31]
Hi,
i hope this can help you to debug EasyCreator, I'm installed EC version 0.0.21  on Joomla 3.3 (update to 3.3.6, but the error was  there in previous Joomla version) and whe i open EC start page i get this error:

/--- start ---/
Errore
EcrProjectTypePlugin::getCoreProjects - Unknown J! version
(... 13 times)
EcrProjectTypePlugin::getCoreProjects - Unknown J! version
/--- stop ---/ 

And if a try to build a component hello world i get this error:

/--- start ---/
Attenzione
EasyCreator 0.0.21 is in testing stage with Joomla! 3.3

Messaggio
buildBase set to: JROOT/administrator/components/com_easycreator/templates/component/mvc_1_16

Build manifest loaded

TempDir created at: JROOT/tmp/com_test5_54b1b6ead3e16

Building: test5 aka "com_test5" Template: mvc_1_16
ERROR

Errore
An error happened while creating your project

EcrProjectTypeComponent::getJoomlaManifestName - Unsupported JVersion

helpers/project/type/component.php (236)

EcrProjectTypeComponent::getDTD - Unsupported JVersion

helpers/project/type/component.php (264)

An error happened while creating your project

controllers/starter.php (52)

ERRORS !

ERROR: Error creating manifest file: no DTD found for 3.3.6 - component Could not save XML file!

/--- stop ---/

Please tell me if i can do some test or if you need other data to best meet your debug needs. Note that  EasyCreator is competing, but is my favourite :) with JDeveloper and Jacc for a little educational  project.

**Comment by elkuku** [comment]
Has been fixed since :wink:
