### ISSUE TITLE
Small fix to do

### ISSUE THREAD

**Issue by francoisgagnon** [elkuku/EasyCreator#33]
Hi,

into file : \administrator\components\com_easycreator\helpers\languagehelper.php
line # from 163 to 166  : change $file->name by $file->fileName
        else
        {
            EcrHtml::message(array(jgettext('File is not UTF-8 encoded'), $file->fileName), 'error');
        }

Other fix :
into file : \administrator\components\com_easycreator\helpers\project\ziper.php
line # 315 - 316  : add (isset($...) &&
        //-- If we are building a "package package", override the preset settings from the package
        //-- with the setting from the request.
        if($this->preset->includeEcrProjectfile
            && (isset($this->buildopts['include_ecr_projectfile']) && true == $this->buildopts['include_ecr_projectfile']))
        {

**Comment by elkuku** [comment]
Could you do a PR please
