### ISSUE TITLE
EasyCreator version 0.0.22 may not work well with your Joomla! version 3.4

### ISSUE THREAD

**Issue by machadoug** [elkuku/EasyCreator#34]
Greetings,

I'm getting the following 2 errors after I've updated to Joomla 3.4.
1. EasyCreator version 0.0.22 may not work well with your Joomla! version 3.4
2. EcrProjectHelper::findManifest - Unknown JVersion

Thanks in advanced for your help,

**Comment by elkuku** [comment]
Hi @machadoug,
I made the necessary changes (I hope) and tagged version 0.0.23
https://github.com/elkuku/EasyCreator/releases/tag/0.0.23

Could you check if it's working for you?

Thanks for reminding!

**Comment by machadoug** [comment]
Dear @elkuku,

Many thanks for the fix.

Unfortunately upgrding didn't work, it asked me to uninstall first. I didn't want to loose all configuration, so I've replaced the admin and site files instead.

All the best,

Douglas
