### ISSUE TITLE
ECr-023 missing XML-File

### ISSUE THREAD

**Issue by hgh-esn** [elkuku/EasyCreator#35]
Hi,

tried to install ECr-023 in J340.
Getting error-message:  no installation-package found.

Can you help?

**Comment by dewebmeester** [comment]
Same problem here. Using developer package:
"Error, No file selected. Unable to find install package"

**Comment by Bodge-IT** [comment]
This is a known bug after upgrade to Joomla 3.4.0.
Either wait for soon to be released 3.4.1 or follow this instruction:
https://www.rsjoomla.com/blog/view/294-fixing-the-joomla-340-extensions-installer-bug.html

**Comment by dewebmeester** [comment]
Thanks for your quick reply. It worked by using the install from url
feature,
Kind regards,
Meindert

2015-03-11 16:09 GMT+01:00 Gary Barclay <notifications@github.com>:

> This is a known bug after upgrade to Joomla 3.4.0.
> Either wait for soon to be released 3.4.1 or follow this instruction:
>
> https://www.rsjoomla.com/blog/view/294-fixing-the-joomla-340-extensions-installer-bug.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elkuku/EasyCreator/issues/35#issuecomment-78282009>.
>



-- 
[image: photo]
Dewebmeester NL
Meindert A. jorna (Msc.)
  T./Fax 0031 317 795149 *|* M. 0031 6 412 86716 *|* info@dewebmeester.nl
*|* Spiderman Webdesign Wageningen *|* Wageningen *|*
http://www.dewebmeester.nl
http://www.decmsmeester.nl
http://www.cheap-web.nl

**Comment by hgh-esn** [comment]
Thanks a lot to all of you.

I did the patch and all is well.
regards HGH

**Comment by hgh-esn** [comment]
closed because it is ok now
