### ISSUE TITLE
Install problem - 0.0.24

### ISSUE THREAD

**Issue by it2semi** [elkuku/EasyCreator#40]
Hello,

I've a install issue with the version 0.0.24 (Joomla: 3.5.0)

Warning
JInstaller: :Install: File does not exist /var/www/domain.tld/public_html/tmp/install_570370cbbc752/EasyCreator-0.0.24/admin/CHANGELOG.php
Component Install: Failed to copy administrator files.
Error
Error installing component

The path to the tmp folder does exist and I have no problem installing other components. 

Where is the problem? What can I do?

**Comment by elkuku** [comment]
Sorry, my fault... Has been fixed.

Thanks for reporting!
