### ISSUE TITLE
Error installation on Joomla 3.7.0 ?

### ISSUE THREAD

**Issue by jmgroud** [elkuku/EasyCreator#46]
Hello
I can't install the component EasyCreator and documentation "not found"

**Error messages on install**
Alerte
JFolder::create: Impossible de créer le répertoirePath: /homepages/27/d203673211/htdocs/ambiances-musicales/tmp/install_5912f35764c6b
Erreur
Unable to create destination
Impossible de trouver un pack d'installation

**Error on documentation**
Documentation can't be found on joomla-wiki.de/elkuku/EasyCreator (https://docs.joomla.org/Main_Page/de/joomla-dokumentation/Benutzer:Elkuku/Proyektz/EasyCreator)
have Fun, =;)
????

**Version EasyCreator** : 0.0.24.1 (downloaded on https://github.com/elkuku/EasyCreator/releases)
**Version Joomla** : 3.7.0 Stable [ Amani ] 25-April-2017 15:36 GMT 
**Version PHP** : 7.1.4 (Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux )
**Version MySQL** : 5.5.55-0+deb7u1-log 
**Provider** : 1&1
(for security, i'm using "**Admin Tools**" version 4.1.3)

Thank you a lot for your help !
Jean-Marie

**Comment by elkuku** [comment]
Sorry, has this been solved? :blush:

**Comment by jmgroud** [comment]
Hello
I stayed several days without knowing how to fix this problem. So I abandoned the discovery of this component.
I may come back to another day ...
Jean Marie
