### ISSUE TITLE
Installing templates gets SSL error

### ISSUE THREAD

**Issue by Bodge-IT** [elkuku/EasyCreator#55]
SSL certificate problem: unable to get local issuer certificate

Is this some issue at my end?

**Comment by elkuku** [comment]
> Is this some issue at my end?

I'd say yes 😉 

First of all - could you give me some more information about your system/environment please?

I have to confess that I released this feature without having it tested on windows&trade; 😞 

So on the first windows test I hit an error similar to the one you posted. I tried again and the error disappeared, but several others popped up...

After correcting those I was able to use the feature on a win10/xampp installation.

**Comment by Bodge-IT** [comment]
Hi Nikolai,
Running on Win7sp1(x64), Wamp Srvr3 (php7,apache2.4,mysql5.7)

I ran into some errors/warning on initial install but these seemed to disappear after cache clean and site load.

The SSL issues arise from  
webapp-v1.0.zip
plugin-custom-folder-v1.0.zip

Actually all of them.

**Comment by elkuku** [comment]
Hi, I've added another parameter that *might* help to solve the SSL issue...
Could you download and test https://github.com/elkuku/EasyCreator/archive/master.zip please?
THANKS!

**Comment by Bodge-IT** [comment]
That did the trick Nikolai...installed no problem and available for creation of new projects....

Thank you!

**Comment by elkuku** [comment]
Glad that helped and thanks a lot for reporting :wink:

Am 24.10.2017 16:54 schrieb "Gary Barclay" <notifications@github.com>:
