### ISSUE TITLE
Error while uninstalling a package

### ISSUE THREAD

**Issue by designfire** [elkuku/EasyCreator#8]
I created a package containing a component, a libraray and a plugin with your amazing EasyCreator. The installation of this package on a test installation of Joomla works fine. 

However when uninstalling this package Joomla tells me that some of those elements could not be uninstalled. I checked it and except from the plugin everything was uninstalled. So the plugin could not be uninstalled. 

I checked the generated package XML and it says there for the plugins id "plg_user_regexport". In the database in table "#__extensions" the plugins name in column "elemnt" is "regexport". Could it be that Joomla searches for "plg_user_regexport" and can't find the plugin because of that? How is the id in the package xml generated?

I created the plugin without EasyCreator and added it to EasyCreator later. Maybe this information helps you finding the problem. 

Please tell me if you need more informations. Thanks for your help!

**Comment by elkuku** [comment]
Should be fixed with #26
